name: Build image and push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest #

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-demo-image:${{ github.sha }}

    - name: Tag image with Registry
      run: docker tag my-demo-image:${{ github.sha }} my-registry/my-demo-image:${{ github.sha }}

    - name: Push to Registry
      run: echo "docker push my-registry/my-demo-image:${{ github.sha }}"

    - name: Aqua CI/CD scan
      run: docker run -d  registry.aquasec.com/scanner:2501.24.29 daemon --token 112ad039aaa587da277645acec280baa39bcd5baf0c4b5970e73fe735fd6e3e9 --host https://198416baaa.cloud.aquasec.com
    
